# @package _global_

defaults:
  - data: collide2v_ad
  - preprocess: collide2v
  - model: ae
  - callbacks: default
  - logger: mlflow
  - trainer: gpu
  - paths: fm_testing
  - extras: default
  - hydra: default

  - experiment: ad_ae

  - _self_

task_name: "eval"

logger:
  mlflow:
    run_name: "best_run_evaluation"
    experiment_name: "anomaly_detection"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: null
use_trial_config: true
